### ISSUE TITLE
vdb dir not available

### ISSUE THREAD

**Issue by jeffbaumes** [trelliscope/trelliscopejs-lib#1]
After `npm install`, `npm run build`, and `npm run start`, I can go to the main page but I get this error:

```
index.js:139 GET http://localhost:3000/vdb/displayList.json 404 (Not Found)
```

**Comment by hafen** [comment]
I've pushed some updates that will fix this.  The vdb (visualization database) example folder I've been using for development is quite large as it holds panels for nearly 3000 plots and I didn't want to bloat the repository with it, so I have now separated things so that you can access a vdb folder from potentially anywhere.

The viewer is independent from any visualization database that it is meant to view, so that you can easily swap out different databases.  I have updated the code so that a config file is used to point to the location of the visualization database, and by default it points to one that I've pushed to another repository.

`npm start` should give you something to work with now out of the box.  If you want a completely offline solution, you can clone the [vdb](https://github.com/hafen/trelliscopejs_vdb_housing) and change the config to point to it locally.

**Comment by jeffbaumes** [comment]
Works perfectly now, thanks! Nice README as well.
