### ISSUE TITLE
Font path seems to be hard-coded vs. relative to where its referenced in the css

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#584]

**Comment by hafen** [comment]
While doing this, if it is possible to make the file paths shorter that would be nice too.

For example, the paths to the fonts can look like this:

```
static/media/opensans-light-webfont.45f52bd42a7b7465602a.woff2
```

R doesn't like long paths because it can lead to portability issues when installing the package on different systems.

This isn't a huge deal but if it's possible to influence the file names, that would be great.
